# Generated by Django 5.0.6 on 2024-06-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorders',
            name='amount',
            field=models.IntegerField(db_column='amount', default=1),
        ),
        migrations.RenameField(
            model_name='productsorders',
            old_name='amount',
            new_name='_amount',
        ),
        migrations.AddField(
            model_name='products',
            name='composition',
            field=models.TextField(default='состав не указан'),
        ),
    ]
